const Data = [
  {
    id: 1,
    category: "education",
    icon: "icon-graduation",
    year: "2017 - 2021",
    title: "BSC in CIS",
    desc: "Daffodil International University",
  },
  {
    id: 2,
    category: "education",
    icon: "icon-graduation",
    year: "2019 - 2019 (3 month)",
    title: "Mobile application development, Android",
    desc: "Bangladesh Association of Software and Information Services (BASIS)",
  },
  {
    id: 3,
    category: "education",
    icon: "icon-graduation",
    year: "2014 - 2016",
    title: "HSC",
    desc: "Mohammadpur Preparatory School and College .",
  },
  {
    id: 4,
    category: "education",
    icon: "icon-graduation",
    year: "2014",
    title: "SSC",
    desc: "Ganabhaban Government High School.",
  },
  {
    id: 4,
    category: "experience",
    icon: "icon-briefcase",
    year: "2021 - present (Fulltime)",
    title: "Client Assistant",
    desc: "Getweb Limited.",
  },
  {
    id: 5,
    category: "experience",
    icon: "icon-briefcase",
    year: "july, 2023 - continue (Part Time)",
    title: "Junior Front-end (React) Developer",
    desc: "KGeCom Limited.",
  },
  {
    id: 6,
    category: "experience",
    icon: "icon-briefcase",
    year: "may, 2023 - jun, 2023 (Part Time)",
    title: "Intern Software engineer",
    desc: "City Explorer - Live Streaming Hub.",
  },
  {
    id: 7,
    category: "experience",
    icon: "icon-briefcase",
    year: "jul, 2021 - Oct, 2021",
    title: "Intern Software engineer",
    desc: "Daffodil Software Limited (DSL) .",
  },
];

export default Data;
